// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNSdnLLsaumxcxMrUPNm9onomcqiovkoM',
    appId: '1:134564869693:web:5bcf16b2c940afdb5b1c54',
    messagingSenderId: '134564869693',
    projectId: 'weather-app-duongtu-2026',
    authDomain: 'weather-app-duongtu-2026.firebaseapp.com',
    storageBucket: 'weather-app-duongtu-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxXz8B9mYWmTseEh9tXtxfn4oQ4U5q4E',
    appId: '1:134564869693:android:8512195d9e5b9b8e5b1c54',
    messagingSenderId: '134564869693',
    projectId: 'weather-app-duongtu-2026',
    storageBucket: 'weather-app-duongtu-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KlasdjJ2vWmwXbrxA-UptQfGi1NJu5s',
    appId: '1:134564869693:ios:6aabf67a5420db825b1c54',
    messagingSenderId: '134564869693',
    projectId: 'weather-app-duongtu-2026',
    storageBucket: 'weather-app-duongtu-2026.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );
}
